name: cipipeline

trigger:
- main

pool:
  name: adopool

jobs:
- job: PowerShellJob
  displayName: 'PowerShell Job'

  steps:
  - task: PowerShell@2
    displayName: 'Run PowerShell Script'
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "Hello Shannu"


pool: vistara-agents

stages:
- stage: planwaStage
  displayName:Palanwa
  jobs: 
  - job: palanwajob
    displayName: Palanwa
    steps:
    - task: 